@startuml container-diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN()

ContainerDb(db_metadata_store, "Metadata store", "SOLR database", "Searchable discovery metadata store.")
ContainerDb(file_metadata_store, "Metadata store", "file system", "Backup discovery metadata store.")
Container(metadata_exporter, "Discovery metadata exporter", "Python", "Retrieves and translates discovery metadata from NetCDF-CF files to internal metadata format (XML).")
ContainerDb(datastore, "Data and Metadata Store and Access", "Files", "A collection of datasets (i.e., data records and the associated information content) in NetCDF-CF format with ACDD metadata.")
SystemDb_Ext(oscar, "OSCAR", "Web resource with WIGOS metadata for all surface-based observing stations and platforms.")


SHOW_LEGEND()

@enduml
